#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  5 10:01:06 2020

@author: dmelgarm
"""

from obspy import read,UTCDateTime
import matplotlib.pyplot as plt

scale=86400
e1=read('/Users/dmelgarm/Parkfield_slowslip/unr_5min/P540/P540.LYE.mseed')
e2=read('/Users/dmelgarm/Parkfield_slowslip/unr_5min/P542/P542.LYE.mseed')

t0=UTCDateTime('2000-01-01T:00:00:00')

t1=(e1[0].stats.starttime-t0)/scale
t2=(e2[0].stats.starttime-t0)/scale

plt.figure()
plt.plot(e1[0].times()/scale+t1,e1[0].data,label='P540')
plt.plot(e2[0].times()/scale+t2,e2[0].data,label='P542')
plt.grid()
plt.legend()
plt.xlabel('Days since 2000-01-01')
plt.ylabel('East (m)')
plt.show()